#!/usr/bin/env python3
from argparse import ArgumentParser


parser = ArgumentParser()
parser.add_argument('--bs', type=int, default=32)
parser.add_argument('--lr', default=0.0001)


if __name__ == '__main__':
    pass
